float detune_amount = 0.001;
uint8_t filter_envelope_depth_cc_value = 0;
uint8_t filter_lfo_depth_cc_value = 0;
uint8_t held_notes[HELD_NOTES_COUNT];
bool is_glide_enabled = true;
bool is_legato_enabled = true;
float note_velocity_to_volume_depth = 0.0;
float pitch_envelope_decay_time_ms = 1.0;
float pitch_envelope_depth = 0.0;
float semitone_offset = 0.0;