float detune_amount = 0.001;
float filter_envelope_depth = 0;
float filter_lfo_1_depth = 0;
float filter_lfo_2_depth = 0;
float filter_velocity_depth = 0.25;
uint8_t held_notes[HELD_NOTES_COUNT];
bool is_glide_enabled = true;
bool is_legato_enabled = true;
float pitch_envelope_decay_time_ms = 1.0;
float pitch_envelope_depth = 0.0;
float semitone_offset = 0.0;